### ISSUE TITLE
Surprise ball may get gone when under the low resolution

### ISSUE THREAD

**Issue by Gabirel** [Gabirel/next-geek#46]
### Expected behavior
Surprise ball shouldn't get lost when under the low resolution(1366*768)

### Actual behavior

![screenshot_2017-06-11_18-34-32](https://user-images.githubusercontent.com/12933851/27010330-bd713206-4ed4-11e7-9820-dd2a717d3af1.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release   ✔
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces
  -  Mala    ✔

**Comment by Gabirel** [comment]
Maybe I can just make `1000` to the small number or make it adjust to the size of screen automatically.

https://github.com/Gabirel/next-geek/blob/master/layout/_partials/suprise/ball.swig#L1546

```css
100% {-webkit-transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1000, 245, 1, 1)}}
```

https://github.com/Gabirel/next-geek/blob/master/layout/_partials/suprise/ball.swig#L1549
```css
0% {-webkit-transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1000, 245, 1, 1)}
```

https://github.com/Gabirel/next-geek/blob/master/layout/_partials/suprise/ball.swig#L3012
```css
100% {-moz-transform: matrix(1, 0, 0, 1, 1000px, 245px)}}
```

https://github.com/Gabirel/next-geek/blob/master/layout/_partials/suprise/ball.swig#L3015
```css
0% {-moz-transform: matrix(1, 0, 0, 1, 1000px, 245px)}
```
